- name: Create Hive user
  ansible.builtin.user:
    name: "{{ hive_user }}"
    group: "{{ hive_group }}"
    create_home: yes
    shell: /bin/bash
    state: present

- name: Create SSH directory for hive user
  ansible.builtin.file:
    path: "/home/{{ hive_user }}/.ssh"
    state: directory
    owner: "{{ hive_user }}"
    group: "{{ hive_group }}"
    mode: '0700'

# Generate SSH key for hive user on master node
- name: Generate SSH key for hive user on master node
  ansible.builtin.openssh_keypair:
    path: "/home/{{ hive_user }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    owner: "{{ hive_user }}"
    group: "{{ hive_group }}"
    mode: '0600'
  when: inventory_hostname == groups['master'][0]

# Copy hive public key to slaves
- name: Copy hive public key to slaves
  ansible.builtin.fetch:
    src: "/home/{{ hive_user }}/.ssh/id_rsa.pub"
    dest: "tmp/hive_id_rsa.pub"
    flat: yes
  when: inventory_hostname == groups['master'][0]

- name: Distribute hive public key to all nodes
  ansible.builtin.copy:
    src: "{{ hostvars[groups['master'][0]]['ansible_facts']['hostname'] }}/tmp/hive_id_rsa.pub"
    dest: "/home/{{ hive_user }}/.ssh/authorized_keys"
    owner: "{{ hive_user }}"
    group: "{{ hive_group }}"
    mode: '0600'

- name: Add all hosts to hive user's known_hosts
  ansible.builtin.known_hosts:
    path: "/home/{{ hive_user }}/.ssh/known_hosts"
    name: "{{ item }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -H ' + item) }}"
    owner: "{{ hive_user }}"
    group: "{{ hive_group }}"
    mode: '0644'
  with_items: "{{ groups['all'] }}"
