# tasks/hadoop_configure.yml
# 6. Configure Hadoop environment and files
- name: Copy hadoop-env.sh
  ansible.builtin.template:
    src: hadoop-env.sh.j2
    dest: "{{ hadoop_conf_dir }}/hadoop-env.sh"
    owner: "{{ hdfs_user }}"
    group: "{{ hadoop_group }}"
    mode: '0644'

- name: Configure core-site.xml
  ansible.builtin.template:
    src: core-site.xml.j2
    dest: "{{ hadoop_conf_dir }}/core-site.xml"
    owner: "{{ hdfs_user }}"
    group: "{{ hadoop_group }}"
    mode: '0644'

- name: Configure hdfs-site.xml
  ansible.builtin.template:
    src: hdfs-site.xml.j2
    dest: "{{ hadoop_conf_dir }}/hdfs-site.xml"
    owner: "{{ hdfs_user }}"
    group: "{{ hadoop_group }}"
    mode: '0644'

# - name: Configure mapred-site.xml
#   ansible.builtin.template:
#     src: mapred-site.xml.j2
#     dest: "{{ hadoop_conf_dir }}/mapred-site.xml"
#     owner: "{{ mapred_user }}"
#     group: "{{ hadoop_group }}"
#     mode: '0644'

- name: Configure yarn-site.xml
  ansible.builtin.template:
    src: yarn-site.xml.j2
    dest: "{{ hadoop_conf_dir }}/yarn-site.xml"
    owner: "{{ yarn_user }}"
    group: "{{ hadoop_group }}"
    mode: '0644'

- name: Copy workers file to master node
  ansible.builtin.template:
    src: workers.j2
    dest: "{{ hadoop_conf_dir }}/workers"
    owner: "{{ hdfs_user }}"
    group: "{{ hadoop_group }}"
    mode: '0644'
  when: inventory_hostname == groups['master'][0]
