# ---
# # tasks file for hadoop role

# tasks/main.yml
- include_tasks: group_setup.yml
- include_tasks: hdfs_setup.yml
- include_tasks: yarn_setup.yml
# - include_tasks: mapreduce_setup.yml
- include_tasks: hadoop_install.yml
- include_tasks: hadoop_configure.yml
- include_tasks: directories_setup.yml
- include_tasks: ownership_adjustments.yml
