---
# tasks file for common role

# - name: Set timezone
#   become: yes
#   community.general.timezone:
#     name: "{{ timezone }}"

- name: Install common packages
  become: yes
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

# - name: Add host entries to /etc/hosts
#   become: yes
#   blockinfile:
#     path: /etc/hosts
#     marker: "# BEGIN ANSIBLE MANAGED HOSTS BLOCK"
#     block: |
#       {% for item in groups['all'] %}
#       {{ hostvars[item]['ansible_host'] }} {{ item }}
#       {% endfor %}

# - name: Add IP address of all hosts to all hosts
#   lineinfile:
#     dest: /etc/hosts
#     regexp: '.*{{ item }}$'
#     line: "{{ hostvars[item].ansible_host }} {{item}}"
#     state: present
#   when: hostvars[item].ansible_host is defined
#   with_items: "{{ groups.all }}"
