---
# tasks file for common role

- name: Set timezone
  community.general.timezone:
    name: {{ timezone }}

- name: Install common packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present